#!/bin/bash

# Catppuccin gradient options:
# "gradient(top_right=0xff94e2d5,bottom_left=0xffcba6f7)" - Teal to Mauve
# "gradient(top_right=0xfff9e2af,bottom_left=0xffeba0ac)" - Yellow to Pink
# "gradient(top_right=0xffa6e3a1,bottom_left=0xff94e2d5)" - Green to Teal
# "gradient(top_right=0xff89b4fa,bottom_left=0xffcba6f7)" - Blue to Mauve

options=(
  style=round
  width=6.0
  hidpi=off
  active_color="gradient(top_right=0xff94e2d5,bottom_left=0xffcba6f7)"
  inactive_color=0xff1e1e2e
)

borders "${options[@]}"
