#!/usr/bin/env bash
# Catppuccin Mocha Theme
source "${CONFIG_DIR}/themes/catppuccin-mocha.sh"

# Bar Properties.
# See: https://felixkratz.github.io/SketchyBar/config/bar
bar=(
  position=top
  height=35
  color="${TRANSPARENT_BASE_2}"
  corner_radius=8
  margin=15
  y_offset=8
)
sketchybar --bar "${bar[@]}"

# Item Properties.
# See: https://felixkratz.github.io/SketchyBar/config/items
default=(
  padding_right=5
  icon.font="JetBrainsMono Nerd Font:Bold:17.0"
  label.font="JetBrainsMono Nerd Font:Regular:14.0"
  icon.color="${SUBTEXT_1}"
  label.color="${SUBTEXT_1}"
  icon.padding_right=4
)
sketchybar --default "${default[@]}"

# Items
# The items stack so the order you enter them is the order
# they will render so for example in Right items since datetime
# is first it will be the furthest right.

# Left Items
source "${CONFIG_DIR}/items/hostname.sh"
source "${CONFIG_DIR}/items/workspaces.sh"

# Center Items
source "${CONFIG_DIR}/items/current_app.sh"

# Right Items
source "${CONFIG_DIR}/items/datetime.sh"
source "${CONFIG_DIR}/items/battery.sh"
source "${CONFIG_DIR}/items/cron.sh"
source "${CONFIG_DIR}/items/slack.sh"

sketchybar --update
