#!/usr/bin/env bash
# Catppuccin Mocha Theme
source "${CONFIG_DIR}/themes/everforest.sh"

# Bar Properties.
# See: https://felixkratz.github.io/SketchyBar/config/bar
bar=(
  position=top
  height=35
  color="${EF_TRANSPARENT_BG_DIM}"
  corner_radius=8
  margin=15
  y_offset=8
)
sketchybar --bar "${bar[@]}"

# Item Properties.
# See: https://felixkratz.github.io/SketchyBar/config/items
default=(
  padding_right=5
  icon.font="BerkeleyMono Nerd Font:Regular:17.0"
  label.font="BerkeleyMono Nerd Font:Regular:14.0"
  icon.color="${EF_GRAY2}"
  label.color="${EF_GRAY2}"
  icon.padding_right=4
)
sketchybar --default "${default[@]}"

# Items
# The items stack so the order you enter them is the order
# they will render so for example in Right items since datetime
# is first it will be the furthest right.

# Left Items
source "${CONFIG_DIR}/items/hostname.sh"
source "${CONFIG_DIR}/items/workspaces.sh"

# Center Items
source "${CONFIG_DIR}/items/current_app.sh"

# Right Items
source "${CONFIG_DIR}/items/datetime.sh"
source "${CONFIG_DIR}/items/battery.sh"

# Work-specific items
# Set in ~/.config/zsh/tokens.zsh on work machines:
#   export WORK_MACHINE=1
#   launchctl setenv WORK_MACHINE 1
if [[ -n "$WORK_MACHINE" ]]; then
  source "${CONFIG_DIR}/items/cron.sh"
  source "${CONFIG_DIR}/items/slack.sh"
fi

sketchybar --update
